### ISSUE TITLE
Shellcode Process Hollowing Issue

### ISSUE THREAD

**Issue by y2kade** [chvancooten/OSEP-Code-Snippets#1]
Hello!  Thank you for posting the code snippets.  They are a great learning resource.  The project builds successfully however I get the following error after running the executable and after the DEBUG: RVA offset value is successfully displayed in the console.

Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range.  Must be non-negative and less than the size of the collection.
Parameter name: startIndex
    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
    at System.BitConverter.ToUInt32(Byte[] value, Int32 startIndex)
    at ProcessHollowing.Program.Main(String[] args)

Based on what I can see, the UInt32 Offset value (under section 4) must be returning a 0 value and I am not sure why?  Any thoughts on what I might be missing?  Thank you in advance.

![gitissue](https://user-images.githubusercontent.com/42455082/127314433-f4f4d606-d32d-481c-9cd9-2fcc27593064.PNG)

**Comment by chvancooten** [comment]
Hi! Thanks, glad to hear the snippets are useful!

It looks like the program is trying to read the bytes at offset `0xe004d4` in an array (`dataBuf`) for which only `0x200` bytes are allocated. This is obviously outside of the buffer and as such throws the out of range error.

Looking at your addresses, it looks like you may have compiled the solution as x86. Could that be the case? If so, please compile it as x64 and try again. If not, could you please supply some more details on how you are compiling and running the solution (OS build, etc), since I'm not able to reproduce the issue currently!

For reference, this is what succesful execution should look like. Notice the difference in offset values!

![image](https://user-images.githubusercontent.com/25614522/127318437-9c21f03f-9946-4a87-b7cc-576df0393dfa.png)

**Comment by y2kade** [comment]
Ah.. ha... My problem that I didn't XOR my payload so I didn't need that portion of the code to decode it.  Once I commented that portion out it worked like a charm.  Thank you for taking the time to respond and help a newbie out.  Cheers!

**Comment by chvancooten** [comment]
Oh interesting, wouldn't have guessed that based on the original error. Thanks for sharing your solution!
